// library/packages/solid/src/components/todo-app/todo-app.tsx
import { For, createSignal, createMemo } from "solid-js";

import { css } from "solid-styled-components";

function TodoApp(props: any) {
  const [list, setList] = createSignal(["hello", "world"]);

  const [newItemName, setNewItemName] = createSignal("");

  function addItem() {
    if (!newItemName()) {
      return;
    }
    setList([...list(), newItemName()]);
  }

  function deleteItem(idx: number) {
    setList(list().filter((x, i) => i !== idx));
  }

  return (
    <div
      class={css({
        padding: "10px",
        maxWidth: "700px",
      })}
    >
      <span>TO-DO list:</span>
      <div
        class={css({
          display: "flex",
          width: "100%",
          gap: "16px",
          alignItems: "stretch",
        })}
      >
        <input
          class={css({
            paddingTop: "0.5rem",
            paddingBottom: "0.5rem",
            paddingLeft: "1rem",
            paddingRight: "1rem",
            borderRadius: "0.25rem",
            flexGrow: "1",
            boxShadow:
              "0 4px 6px -1px rgba(0, 0, 0, 0.1), 0 2px 4px -1px rgba(0, 0, 0, 0.06)",
          })}
          placeholder="Add a new item"
          value={newItemName()}
          onInput={(event) => setNewItemName(event.target.value)}
        />
        <button
          class={css({
            paddingTop: "0.5rem",
            paddingBottom: "0.5rem",
            paddingLeft: "1rem",
            paddingRight: "1rem",
            borderRadius: "0.25rem",
            fontWeight: "700",
            color: "#ffffff",
            backgroundColor: "#3B82F6",
            cursor: "pointer",
          })}
          onClick={(event) => addItem()}
        >
          Add
        </button>
      </div>
      <div
        class={css({
          marginTop: "1rem",
        })}
      >
        <ul
          class={css({
            borderRadius: "0.25rem",
            boxShadow:
              "0 4px 6px -1px rgba(0, 0, 0, 0.1), 0 2px 4px -1px rgba(0, 0, 0, 0.06)",
            margin: "unset",
            padding: "unset",
          })}
        >
          <For each={list()}>
            {(item, _index) => {
              const idx = _index();
              return (
                <li
                  class={css({
                    display: "flex",
                    padding: "0.625rem",
                    alignItems: "center",
                    borderBottomWidth: "1px",
                    borderColor: "#E5E7EB",
                    gap: "16px",
                  })}
                  key={idx}
                >
                  <span>{item}</span>
                  <button
                    class={css({
                      cursor: "pointer",
                      paddingTop: "0.5rem",
                      paddingBottom: "0.5rem",
                      paddingLeft: "1rem",
                      paddingRight: "1rem",
                      borderRadius: "0.25rem",
                      color: "#ffffff",
                      backgroundColor: "#EF4444",
                    })}
                    onClick={(event) => {
                      deleteItem(idx);
                    }}
                  >
                    Delete
                  </button>
                </li>
              );
            }}
          </For>
        </ul>
      </div>
    </div>
  );
}

export default TodoApp;

// library/packages/react-native/src/components/todo-app/todo-app.tsx
import * as React from "react";
import {
  FlatList,
  ScrollView,
  View,
  StyleSheet,
  Image,
  Text,
  Pressable,
  TextInput,
} from "react-native";
import { useState } from "react";

function TodoApp(props: any) {
  const [list, setList] = useState(() => ["hello", "world"]);

  const [newItemName, setNewItemName] = useState(() => "");

  function addItem() {
    if (!newItemName) {
      return;
    }
    setList([...list, newItemName]);
  }

  function deleteItem(idx: number) {
    setList(list.filter((x, i) => i !== idx));
  }

  return (
    <View style={styles.view1}>
      <View>
        <Text>TO-DO list:</Text>
      </View>
      <View style={styles.view2}>
        <TextInput
          placeholder="Add a new item"
          value={newItemName}
          onChange={(event) => setNewItemName(event.target.value)}
          style={styles.textInput1}
        />
        <Pressable onPress={(event) => addItem()} style={styles.pressable1}>
          <Text>Add</Text>
        </Pressable>
      </View>
      <View style={styles.view3}>
        <View style={styles.view4}>
          {list?.map((item, idx) => (
            <View key={idx} style={styles.view5}>
              <View>
                <Text>{item}</Text>
              </View>
              <Pressable
                onPress={(event) => {
                  deleteItem(idx);
                }}
                style={styles.pressable2}
              >
                <Text>Delete</Text>
              </Pressable>
            </View>
          ))}
        </View>
      </View>
    </View>
  );
}

const styles = StyleSheet.create({
  view1: { padding: 10, maxWidth: 700 },
  view2: { display: "flex", width: "100%", gap: 16, alignItems: "stretch" },
  textInput1: {
    paddingTop: "0.5rem",
    paddingBottom: "0.5rem",
    paddingLeft: "1rem",
    paddingRight: "1rem",
    borderRadius: "0.25rem",
    flexGrow: "1",
    boxShadow:
      "0 4px 6px -1px rgba(0, 0, 0, 0.1), 0 2px 4px -1px rgba(0, 0, 0, 0.06)",
  },
  pressable1: {
    paddingTop: "0.5rem",
    paddingBottom: "0.5rem",
    paddingLeft: "1rem",
    paddingRight: "1rem",
    borderRadius: "0.25rem",
    fontWeight: "700",
    color: "#ffffff",
    backgroundColor: "#3B82F6",
    cursor: "pointer",
  },
  view3: { marginTop: "1rem" },
  view4: {
    borderRadius: "0.25rem",
    boxShadow:
      "0 4px 6px -1px rgba(0, 0, 0, 0.1), 0 2px 4px -1px rgba(0, 0, 0, 0.06)",
    margin: "unset",
    padding: "unset",
  },
  view5: {
    display: "flex",
    padding: "0.625rem",
    alignItems: "center",
    borderBottomWidth: 1,
    borderColor: "#E5E7EB",
    gap: 16,
  },
  pressable2: {
    cursor: "pointer",
    paddingTop: "0.5rem",
    paddingBottom: "0.5rem",
    paddingLeft: "1rem",
    paddingRight: "1rem",
    borderRadius: "0.25rem",
    color: "#ffffff",
    backgroundColor: "#EF4444",
  },
});

export default TodoApp;
